---
- name: ensure ssh configuration directory
  file:
    path: "{{ansible_env['HOME']}}/.ssh"
    state: directory
    recurse: yes

- name: ensure github is a known host
  lineinfile:
    dest: "{{ansible_env['HOME']}}/.ssh/known_hosts"
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com 2>/dev/null') }}"
    regexp: "^github\\.com"
