---
- name: install build requirements
  become: yes
  apt: name={{item}} state=present
  with_items:
    - autoconf
    - autogen
    - build-essential
    - libtool

- name: fetch libsodium source
  become: yes
  shell: |
    LIBSODIUM_VERSION="1.0.15" && \
    LIBSODIUM_DOWNLOAD_URL="https://download.libsodium.org/libsodium/releases/libsodium-${LIBSODIUM_VERSION}.tar.gz" && \
    LIBSODIUM_DOWNLOAD_SHA256="fb6a9e879a2f674592e4328c5d9f79f082405ee4bb05cb6e679b90afe9e178f4" && \
    curl -fSL -o libsodium-src.tar.gz "${LIBSODIUM_DOWNLOAD_URL}" && \
    echo "$LIBSODIUM_DOWNLOAD_SHA256  libsodium-src.tar.gz" | sha256sum -c - && \
    mkdir -p /usr/local/src/libsodium && \
    tar -xzC /usr/local/src/libsodium --strip-components=1 -f libsodium-src.tar.gz && \
    rm libsodium-src.tar.gz
  args:
    creates: /usr/local/src/libsodium/autogen.sh
    warn: no

- name: build libsodium
  become: yes
  shell: |
    ./autogen.sh && \
    ./configure && \
    make && \
    make check && \
    make install
  args:
    chdir: /usr/local/src/libsodium
    creates: /usr/local/lib/libsodium.so
